export const PAGE_LOAD = 'PAGE_LOAD';
export const PAGE_UNLOAD = 'PAGE_UNLOAD';
export const ERROR_FLAG = 'ERROR_FLAG';
export const ALERT_CLOSE = 'ALERT_CLOSE';
export const ALERT_OPEN = 'ALERT_OPEN';
export const ALERT_CLOSE_UNSTICKY= 'ALERT_CLOSE_UNSTICKY';
export const FORM_SAVE = 'FORM_CONTACT_SAVE';
export const FORM_LOCK = 'FORM_LOCK';
export const FORM_HIDE = 'FORM_HIDE';